### ISSUE TITLE
Is there any result comparsion with the AIM2019 RAW2RGB TOP1(MOS) solution?

### ISSUE THREAD

**Issue by splinter21** [aiff22/PyNET-PyTorch#16]
https://github.com/MKFMIKU/RAW2RGBNet

**Comment by aiff22** [comment]
Hi @splinter21,

In the previous AIM2019 challenge, a simplified version of the Zurich RAW to RGB dataset was used: it was consisting of 8-bit (instead of 10-bit) images and was not considering image upsampling. Therefore, the results obtained in that challenge cannot be compared with the current ones.
