### ISSUE TITLE
A comparsion with the AIM2020 Image Signal Processing Challenge

### ISSUE THREAD

**Issue by jasonchenPJ** [aiff22/PyNET-PyTorch#21]
The Pynet use the test raw(448x448) of ZRR dataset to evaluate the PSNR result. Are the results comparable to AIM 2020 ISP pipeline challenge results ?
![image](https://user-images.githubusercontent.com/47911137/99327628-4bc00880-28b5-11eb-945f-1be48b588de0.png)

**Comment by aiff22** [comment]
Hi @jasonchenPJ,

No, in the AIM 2020 challenge we used additional test images that are not available publicly.

**Comment by YangGangZhiQi** [comment]
@aiff22  Hi, thanks for your great work. When using your model to inference my local pics with the order of (ch_B, ch_Gb, ch_R, ch_Gr), I get a red rendered results. It seems like there are big difference between the same bayer pattern,eg same [[R,Gr,R, Gr],[Gb,B,Gb,B]]。Is there a solution to transfer local pic to your bayer pattern so that your model could predict correctly. 

- As I known, in 'ISP with deep learning' field, the training dataset are hard to collect. The model with public dataset may not be available to local pictures. I think the transfer method above have great value for practice use or research. Hope for your reply.
