### ISSUE TITLE
Some images look like black

### ISSUE THREAD

**Issue by XGBoost** [aiff22/PyNET-PyTorch#6]
![image](https://user-images.githubusercontent.com/23393128/75983072-c19c6380-5f22-11ea-86ef-b018800b9523.png)
When I unzip the downloaded data, some images in HuaweiP20 raw folder look like black, are these images normal?

**Comment by Jam-G** [comment]
@XGBoost These black images are saved as 16bits uint16 because some pixel is greater than 255. And other gray images are saved as 8bits uint8 for saving hard disk space since all pixels lie between 0 and 255.
And both of them are 10bits depth Bayer pattern raw data.
It looks like black or gray is determined by the default strategy of windows preview. Since the software didn't know about the effective number of bits， when images are saved as 16bits depth , the max value will be 2**16 - 1, but the truly effective number of bits is 10bits， all
 pixels look like darker than it should be. But when they are  saved as 8bits， all pixels look like  brighter than it should be. And actually, the preview  or showing them as png gray images are meaningless，because they are Bayer pattern data but not traditional images.

I have submited an  [issue early](https://github.com/aiff22/PyNET/issues/2) at [PyNET](https://github.com/aiff22/PyNET)， you can find the author‘s reply there.
